### ISSUE TITLE
doesn't seem to work with 1.0 beta4

### ISSUE THREAD

**Issue by davidmonro** [knolleary/pubsubclient#3]
when compiling a sketch I get the following errors. My C++-fu is insufficient to figure this one out :)

Cheers,

David

In file included from MQTTBridge2.cpp:26:
/home/davidm/sketchbook/libraries/PubSubClient/PubSubClient.h:36: error: cannot declare field ‘PubSubClient::_client’ to be of abstract type ‘Client’
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:7: note:   because the following virtual functions are pure within ‘Client’:
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:12: note:     virtual size_t Client::write(uint8_t)
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:13: note:     virtual size_t Client::write(const uint8_t_, size_t)
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:14: note:     virtual int Client::available()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:15: note:     virtual int Client::read()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:17: note:     virtual int Client::peek()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:18: note:     virtual void Client::flush()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:10: note:     virtual int Client::connect(IPAddress, uint16_t)
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:11: note:     virtual int Client::connect(const char_, uint16_t)
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:16: note:     virtual int Client::read(uint8_t*, size_t)
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:19: note:     virtual void Client::stop()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:20: note:     virtual uint8_t Client::connected()
/u5/home/davidm/arduino-1.0-beta4/hardware/arduino/cores/arduino/Client.h:21: note:     virtual Client::operator bool()
